theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Lennart Langouche, PhD
logo: /assets/img/hs.jpg

description: Computational Biologist | Machine Learning Scientist
markdown: kramdown
style: davewhipp
show_downloads: true
github:
  website_url: "https://lenlan.github.io/"
  
  embedded_ig_url: /pages/kitchen_experiments.html
  embedded_twitter_url: /pages/twitter_posts.html
  embedded_cv_url: /pages/cv.html
  embedded_gscholar_url: /pages/google_scholar.html
  embedded_neurotree_url: /pages/neurotree.html
  
  linkedin_url: "https://www.linkedin.com/in/lennart-langouche/"
  googlescholar_url: "https://scholar.google.com/citations?user=EhHicP0AAAAJ&hl=en"
  twitter_url: ""
  instagram_url: ""
  cv_url: ""
  resume_url: ""
  neurotree_url: ""
  
