theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Lennart Langouche, PhD
logo: /assets/img/hs.jpg

description: Computational Biologist | Machine Learning Scientist
markdown: kramdown
style: davewhipp
show_downloads: true
github:
  website_url: "https://lenlan.github.io/"
  
  embedded_ig_url: ""
  embedded_twitter_url: ""
  embedded_cv_url: ""
  embedded_gscholar_url: ""
  embedded_neurotree_url: ""
  
  linkedin_url: "https://www.linkedin.com/in/lennart-langouche/"
  googlescholar_url: "https://scholar.google.com/citations?user=EhHicP0AAAAJ&hl=en"
  twitter_url: ""
  instagram_url: ""
  cv_url: "https://github.com/lenlan/lenlan.github.io/blob/main/pdfs/CV.pdf"
  resume_url: "https://github.com/lenlan/lenlan.github.io/blob/main/pdfs/Resume.pdf"
  neurotree_url: ""
  
